$(function(){
    $(".newcurrent").click(function(){
        $(".addcurrentcontainer").css({display:'block'});
    });
    $("#currentboxexit").click(function(){
        $(".addcurrentcontainer").css({display:'none'});
    });
    $("#cancel").click(function(){
        $(".addcurrentcontainer").css({display:'none'});
    });
});